project_id = "fxlhpizydnbdkhuzrkpr"

[functions.send-pending-reminders]
verify_jwt = false

[functions.create-customer-account]
verify_jwt = false

[functions.decrement-stock]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-order-pending-email]
verify_jwt = false

[functions.send-order-approved]
verify_jwt = false

[functions.get-order-status]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false

[functions.send-review-request]
verify_jwt = false

[functions.send-recompra-campaigns]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.send-cart-reminders]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.send-order-whatsapp]
verify_jwt = false

[functions.test-whatsapp-connection]
verify_jwt = false

[functions.notificame-webhook]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.create-asaas-pix]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.get-pix-details]
verify_jwt = false
