project_id = "fxlhpizydnbdkhuzrkpr"

[functions.send-pending-reminders]
verify_jwt = false

[functions.create-mp-preference]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.create-customer-account]
verify_jwt = false

[functions.decrement-stock]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-order-pending-email]
verify_jwt = false
